### PR TITLE
adding my tests

### PR DESCRIPTION
**Pull request by nikita09**

### CODE REVIEW

**Comment by pscamman** [comment]
Please remove .DS_Store, reduce the number of acceptance tests to 200, and notify a grader on canvas when the pull request is ready again.

**Comment by nikita09** [comment]
Fixed it.

**Comment by cindywu2018** [comment]
Please delete the hidden file .DS_Store. Thanks.

**Comment by nikita09** [comment]
I deleted the file locally, but it still shows up on github. Is there a way I can delete it on github?

**Comment by cindywu2018** [comment]
Go to your local clone of your forked repo, delete the file in your local clone, then push your changes to your forked repo, and then submit another pull request from the fork.

**Comment by nikita09** [comment]
I fixed it with the help of Onur in office hours.

**Comment by pscamman** [comment]
You are missing the single newline at the end of your .out file. The diff command that we must run will fail if it is not present.

**Comment by nikita09** [comment]
fixed

**Pull request merged**
