### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by jmendoza94**

### CODE REVIEW

**Comment by cindywu2018** [comment]
Your acceptance tests should have 100-200 lines. Please add more tests. Thanks.

**Comment by pscamman** [comment]
Further, your current acceptance tests contain overflowing numbers.

**Comment by cindywu2018** [comment]
Are you submitting your most recent changes? I still only see 30 lines...

**Comment by jmendoza94** [comment]
Do you mean I should have 100-200 tests or that my acceptance output (TestCollatz.out) should be 100-200 lines?

**Comment by pscamman** [comment]
You must have 100-200 lines in the RunCollatz.in and RunCollatz.out files.

**Comment by cindywu2018** [comment]
Further, the acceptance tests are RunCollatz.in and RunCollatz.out. 
TestCollatz files contain your unit tests.

**Comment by cindywu2018** [comment]
There are values that result in overflow in your tests. Please fix and resubmit a pull request. Thanks.
Hint: make the numbers smaller.

**Comment by pscamman** [comment]
You still contain overflow.

**Pull request merged**
