### PR TITLE
Added ecb2344 tests.

### PR DESCRIPTION
**Pull request by ebigelow12**
Added ecb2344 tests.

### CODE REVIEW

**Comment by Domanic** [comment]
Your change should have exactly 4 files, please remove ".DS_Store" from your request.

**Comment by ebigelow12** [comment]
I got rid of the .DS_Store. Do I need to close this pull request and make a new one?

**Comment by Domanic** [comment]
It's better to keep this request, I see your change. But your tests have values that result in overflow, please fix them. Also you should put a newline character at the end of your last line in the acceptance test file, (do not create an empty line, just put an "enter" on the last nonempty line).

**Comment by Domanic** [comment]
Your tests still have values that result in overflow, please fix them.

**Comment by ebigelow12** [comment]
I added a new line at the end of ecb2344-RunCollatz.in. There was already a new line using "enter" on ecb2344-RunCollatz.out. And could you elaborate on one of the tests that caused an overflow error? Because I didn't get an overflow error for any of my tests.

**Comment by Domanic** [comment]
See the Piazza, for instance @121, for a list of values that cause overflows. The intervals in your acceptance tests should not include those values.

**Comment by ebigelow12** [comment]
I see what you mean by overflowing now. Did this fix it?

**Comment by Domanic** [comment]
Sorry, there's still at least one overflow.

**Comment by ebigelow12** [comment]
You are right. I missed one. How about now?

**Comment by Domanic** [comment]
So far so good.

**Pull request merged**
