### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by callieko**

### CODE REVIEW

**Comment by pscamman** [comment]
You must have between 100 and 200 lines of acceptance tests, please add more.

**Comment by callieko** [comment]
Added more lines

**Comment by pscamman** [comment]
RunCollatz.in and RunCollatz.out must have a matching number of lines. Also at least one of the lines causes overflow.

**Comment by cindywu2018** [comment]
When in doubt, just use numbers with 5 digits or less.

**Comment by callieko** [comment]
Should be good this time?

**Comment by cindywu2018** [comment]
Please delete the extra files...You accidentally submitted the 4 test files that do not have your EID as well.

**Comment by callieko** [comment]
Ah shoot

**Pull request merged**
