### PR TITLE
Adding all acceptance and unit tests

### PR DESCRIPTION
**Pull request by akhilvelpuri**

### CODE REVIEW

**Comment by pscamman** [comment]
1. There are unnecessary empty lines at the end of your RunCollatz.in
2. Your RunCollatz.in file contains overflowing numbers, please fix and try again

**Comment by iitc** [comment]
Invalid ranges:
```
Range: 502135, 502758 :: [502441]
Range: 502026, 502442 :: [502441]
```

**Comment by Domanic** [comment]
Please make the changes in the files.

**Comment by cindywu2018** [comment]
Make sure you fork the public test repo and submit your pull request from your fork.

**Comment by pscamman** [comment]
Your newer files have been accepted, closing this request.

**Pull request closed without merging**
