### PR TITLE
mdh3365 initial submission

### PR DESCRIPTION
**Pull request by hudsonmd**

### CODE REVIEW

**Comment by rezama** [comment]
There are some test cases in your acceptance test that cause integer overflow.  You can find the list on piazza.  Please remove those and resubmit.

**Comment by pscamman** [comment]
You still contain overflows.

**Comment by iitc** [comment]
Invalid ranges:

```
Range: 418474, 423540 :: [419839, 420351, 420863]
Range: 626788, 630258 :: [629759]
Range: 842761, 846811 :: [844647]
Range: 236610, 246607 :: [239231, 242159, 242303, 245985]
Range: 572888, 579598 :: [574006, 574007, 574347, 575865, 577230, 577231, 579327]
Range: 920207, 926218 :: [920559, 924907]
Range: 366412, 374639 :: [368978, 368979]
Range: 551443, 554886 :: [552295, 553468, 553469, 553470, 553471]
Range: 151112, 151729 :: [151177]
Range: 141858, 151536 :: [151177]
Range: 862937, 867227 :: [863798, 863799, 865846, 865847]
Range: 826061, 832351 :: [827391, 827961, 828443, 829087, 830204, 830205, 830206, 830207]
Range: 280821, 285282 :: [284137]
Range: 559685, 568620 :: [559785, 561150, 561151, 565247, 566719, 567065, 568274, 568275]
Range: 392663, 395287 :: [392959]
Range: 145336, 153040 :: [151177]
Range: 911733, 919538 :: [912167, 917161, 918070, 918071, 919451, 919518, 919519]
Range: 414817, 416131 :: [415102, 415103]
Range: 202918, 209889 :: [204015, 207551]
Range: 251386, 259340 :: [255113, 258207]
Range: 977210, 981663 :: [978943, 980383, 981287]
Range: 107863, 115433 :: [113383]
Range: 611508, 619868 :: [612046, 612047, 612967]
Range: 816421, 821434 :: [816815, 817289, 817775]
Range: 569650, 578926 :: [574006, 574007, 574347, 575865, 577230, 577231]
Range: 129411, 138141 :: [134379]
Range: 280182, 282119 :: [280575]
Range: 786215, 790034 :: [786431, 787739, 788583]
Range: 982172, 987446 :: [983039, 983940, 983941, 983942, 983947, 984623]
Range: 944119, 945613 :: [944639, 945435]
Range: 524869, 526829 :: [525159]
Range: 424269, 433469 :: [425298, 425299, 426206, 426207, 430505, 430761, 431899, 432923]
Range: 710463, 717164 :: [713575, 716689, 716690, 716691]
Range: 856452, 860027 :: [856731, 859135, 859719]
Range: 278113, 287091 :: [280575, 284137, 287003]
Range: 817225, 818068 :: [817289, 817775]
Range: 650353, 654318 :: [650889, 654191]
Range: 950242, 956696 :: [951433, 955585, 955586, 955587, 955591]
Range: 541087, 549580 :: [542959, 544041, 544543, 544859, 545183]
Range: 813647, 823278 :: [814439, 815871, 816060, 816061, 816062, 816815, 817289, 817775, 822139]
Range: 415024, 420153 :: [415102, 415103, 419839]
Range: 863112, 867453 :: [863798, 863799, 865846, 865847]
Range: 134306, 140455 :: [134379, 138367]
Range: 856166, 865477 :: [856731, 859135, 859719, 861009, 861010, 861011, 861521, 861522, 861523, 863798, 863799]
Range: 514008, 519706 :: [516414, 516415, 516891, 517191]
Range: 311195, 311673 :: [311327]
Range: 629189, 633065 :: [629759, 630527, 631295]
Range: 696152, 699210 :: [698593, 699049]
Range: 149027, 155169 :: [151177]
Range: 881639, 885192 :: [882815, 884159]
Range: 339130, 345911 :: [340150, 340151]
Range: 855325, 864056 :: [856731, 859135, 859719, 861009, 861010, 861011, 861521, 861522, 861523, 863798, 863799]
Range: 244396, 250548 :: [245985]
Range: 841363, 849093 :: [841726, 841727, 844647, 847871]
Range: 970706, 978780 :: [971774, 971775, 974078, 974079, 975015, 976334, 976335]
Range: 564152, 572727 :: [565247, 566719, 567065, 568274, 568275]
Range: 166027, 172719 :: [170075]
Range: 686040, 689075 :: [687871, 688553]
Range: 508306, 512863 :: [510226, 510227]
Range: 650291, 658103 :: [650889, 654191, 654571, 654619, 655359, 655961, 656415]
Range: 523818, 532196 :: [523945, 524287, 525159, 531183]
Range: 774320, 782829 :: [774622, 774623, 775337, 775787, 777435, 777438, 777439, 780391, 780735, 781951, 782335]
Range: 611806, 619816 :: [612046, 612047, 612967]
Range: 572281, 580882 :: [574006, 574007, 574347, 575865, 577230, 577231, 579327]
Range: 804953, 811131 :: [806276, 806277, 806278, 806283, 807407, 809129, 810814, 810815]
Range: 253391, 257340 :: [255113]
Range: 540733, 550665 :: [542959, 544041, 544543, 544859, 545183]
Range: 766296, 773698 :: [769641]
Range: 147672, 154221 :: [151177]
Range: 648449, 652656 :: [649385, 650889]
Range: 745736, 753510 :: [747291, 748031, 748201, 750831]
Range: 182266, 187470 :: [184489]
Range: 281479, 288113 :: [284137, 287003]
Range: 709010, 714925 :: [713575]
Range: 725440, 734370 :: [726057, 726478, 726479, 726910, 726911, 728831, 730559, 732251]
Range: 362272, 364830 :: [363239, 363455]
Range: 491424, 495071 :: [491970, 491971]
Range: 506537, 515198 :: [510226, 510227]
Range: 164287, 171664 :: [170075]
Range: 607027, 615908 :: [608111, 612046, 612047, 612967]
Range: 979906, 983295 :: [980383, 981287, 981857, 981929, 983039]
Range: 898881, 902216 :: [901119]
Range: 638407, 648092 :: [639310, 639311, 640641, 645756, 645757, 645758, 645759, 646140, 646141, 646142, 647849]
Range: 634026, 642273 :: [637057, 637948, 637949, 637950, 639310, 639311, 640641]
Range: 819895, 826649 :: [822139, 823783, 824187]
Range: 507792, 514251 :: [510226, 510227]
Range: 888248, 892586 :: [889833]
Range: 418166, 422873 :: [419839, 420351, 420863]
Range: 786738, 791700 :: [787739, 788583]
Range: 354302, 360096 :: [358345, 358847]
```

**Comment by Domanic** [comment]
Please make the change in the files.

**Pull request closed without merging**
