### PR TITLE
Added my files.

### PR DESCRIPTION
**Pull request by Gilbert-Maldonado**

### CODE REVIEW

**Comment by cindywu2018** [comment]
Your numbers are valid so far, but please add more lines to your tests. Thank you.

**Comment by Gilbert-Maldonado** [comment]
Add more acceptance tests? What do you mean by that?

**Comment by cindywu2018** [comment]
Your RunCollatz.in and RunCollatz.out should have 100-200 lines of numbers.

**Comment by cindywu2018** [comment]
Thank you.

**Pull request merged**
