### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by jchurchman100**

### CODE REVIEW

**Comment by Domanic** [comment]
Can you please delete the empty line at the end of jlc5526-RunCollatz.in?

**Comment by pscamman** [comment]
Further, your .out file must end with a newline character. This is not the same as having a full blank line at the end, however.

**Comment by pscamman** [comment]
Newline is \n not /n. It must look like the end of the green box for .out in this example: https://github.com/cs371p-fall-2016/collatz-tests/pull/260/files

**Comment by pscamman** [comment]
Here is your code. Look at the bottom of the green box for your .out and compare to the other link:
https://github.com/cs371p-fall-2016/collatz-tests/pull/170/files

Please update the file and check that link until it is correct.

**Pull request merged**
