### PR TITLE
giving my test to repo

### PR DESCRIPTION
**Pull request by jcorona08**

### CODE REVIEW

**Comment by pscamman** [comment]
1. Remove .DS_Store from the submission
2. You have 2 newline characters at the end of your RunCollatz.out instead of exactly 1
3. You have more than 100-200 lines of acceptance tests

Please fix these issues and notify a grader on canvas.

**Comment by pscamman** [comment]
1. Remove .DS_Store from the submission
2. You have more than 100-200 lines of acceptance tests

**Comment by jcorona08** [comment]
Hi, 
I think I removed the acceptance tests. Please let me know if they are reflected on your side. I also cant seem to figure out how to remove the .DS_Store file. Do you mind telling me how to do it? 

Thanks

**Comment by pscamman** [comment]
Yes, your acceptance tests are fine now. To remove the .DS_Store I believe you must simply navigate to the repo in your terminal, type `rm .DS_Store`, type `git status` to make sure it says the file has been deleted, then simply commit and push. Once it no longer shows up [here](https://github.com/cs371p-fall-2016/collatz-tests/pull/245/files) the pull request is good to go.

Thanks

**Comment by jcorona08** [comment]
Cool I think I got it. Let me know if its reflected on your side. Thanks!

**Comment by pscamman** [comment]
Looks good!

**Pull request merged**
