### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by btorio**
Here are my tests for the test repo.

### CODE REVIEW

**Comment by pscamman** [comment]
Please remove .DS_Store from your files.

**Comment by pscamman** [comment]
Also, your RunCollatz.in file and RunCollatz.out file have a mismatched number of lines. Finally, make sure RunCollatz.in and RunCollatz.out both end with a single newline character, not 0 and 2 like they do now respectively.

**Comment by btorio** [comment]
Ok, I will fix it. Thanks.

**Comment by btorio** [comment]
I think I have fixed those two things, sorry for the misunderstanding.

**Comment by pscamman** [comment]
No problem.

**Pull request merged**
