### PR TITLE
Added tests for Samuel Braley (szb82)

### PR DESCRIPTION
**Pull request by samuelbraley**

### CODE REVIEW

**Comment by Domanic** [comment]
The number of acceptance tests should be between 100 and 200. Can you please fix them?

**Comment by samuelbraley** [comment]
Done!

**Comment by Domanic** [comment]
You forgot to remove them from the .out file, can you please fix it?

**Comment by samuelbraley** [comment]
Sorry, done!

**Comment by Domanic** [comment]
Your tests have values that result in overflow, can you please fix them?

**Comment by samuelbraley** [comment]
Sorry about all that, should be good now.

**Comment by samuelbraley** [comment]
@Domanic Would you mind checking my pull request to see if it's all good? Thanks!

**Pull request merged**
