### PR TITLE
RunCollatz.in and RunCollatz.out recreated in cs machine

### PR DESCRIPTION
**Pull request by wonkgo1**

### CODE REVIEW

**Comment by wonkgo1** [comment]
gk4893-RunCollatz.in and gk4893-RunCollatz.out recreated in cs machine so it should have correct line endings. Let me know it's correct or not

**Comment by xsznix** [comment]
Line endings LGTM

**Comment by xsznix** [comment]
This PR fixes #131.

**Comment by wonkgo1** [comment]
Does that mean it's been fixed? So I don't have to worry about this?

**Comment by xsznix** [comment]
[Yes](https://www.urbandictionary.com/define.php?term=LGTM&defid=2535452), thanks.

**Pull request closed without merging**
