### PR TITLE
Melody's Public Tests

### PR DESCRIPTION
**Pull request by myopark**

### CODE REVIEW

**Comment by cindywu2018** [comment]
Please don't add others students' tests in your pull request. Just your own 4 test files. Thanks!

**Comment by xsznix** [comment]
Probably a good idea to fork this repo rather than my fork of this repo for your tests. Perhaps rebase your work on the right upstream?

**Comment by rezama** [comment]
myopark, did you resolve this issue?

**Comment by myopark** [comment]
I just submitted another pull request that will hopefullg work

**Comment by rezama** [comment]
Deleting this one then.

**Pull request closed without merging**
