### PR TITLE
added files

### PR DESCRIPTION
**Pull request by kevinsalcedo**

### CODE REVIEW

**Comment by Domanic** [comment]
Your change should have exactly 4 files, please remove ".DSStore" from your request.

**Comment by kevinsalcedo** [comment]
i'm fairly new to github, what is the best way to go about doing that? on the site, or on the terminal?

**Comment by Domanic** [comment]
I haven't played with pull requests either, but I think easiest way would be to make the change on the master branch on your fork (kevinsalcedo/collatz-tests).

**Comment by kevinsalcedo** [comment]
i think i have just four files now?

**Comment by kevinsalcedo** [comment]
let me know if they aren't the right files, this honestly really confuses me.

**Comment by Domanic** [comment]
Looks OK now, just checked for overflows and didn't see any.

**Comment by kevinsalcedo** [comment]
alright, awesome! thank you!

**Pull request merged**
