### PR TITLE
added files

### PR DESCRIPTION
**Pull request by DinhH**

### CODE REVIEW

**Comment by Domanic** [comment]
Hi, your tests have values that result in overflow, please fix them.

**Comment by pscamman** [comment]
You still contain overflow.

**Comment by iitc** [comment]
Invalid ranges:

```
Range: 335678, 8657 :: [113383, 134379, 138367, 151177, 159487, 161439, 161535, 170075, 184489, 191335, 201569, 204015, 207551, 212649, 213103, 226766, 226767, 239231, 242159, 242303, 245985, 255113, 258207, 268758, 268759, 270271, 276734, 276735, 280575, 284137, 287003, 288615, 290751, 302354, 302355, 306023, 311327, 318974, 318975, 319655, 322878, 322879, 323070, 323071]
Range: 35677, 899537 :: [113383, 134379, 138367, 151177, 159487, 161439, 161535, 170075, 184489, 191335, 201569, 204015, 207551, 212649, 213103, 226766, 226767, 239231, 242159, 242303, 245985, 255113, 258207, 268758, 268759, 270271, 276734, 276735, 280575, 284137, 287003, 288615, 290751, 302354, 302355, 306023, 311327, 318974, 318975, 319655, 322878, 322879, 323070, 323071, 340150, 340151, 358345, 358847, 360361, 363239, 363455, 368978, 368979, 376831, 378043, 378849, 382670, 382671, 387311, 388719, 392959, 403138, 403139, 405407, 408030, 408031, 415102, 415103, 419839, 420351, 420863, 425298, 425299, 426206, 426207, 430505, 430761, 431899, 432923, 436127, 437307, 453532, 453533, 453534, 453535, 459035, 459759, 466991, 477793, 478462, 478463, 479483, 480481, 483591, 484318, 484319, 484606, 484607, 485887, 487039, 488167, 491970, 491971, 498687, 502441, 504057, 510226, 510227, 516414, 516415, 516891, 517191, 523945, 524287, 525159, 531183, 537516, 537517, 537518, 538271, 539419, 540542, 540543, 542959, 544041, 544543, 544859, 545183, 552295, 553468, 553469, 553470, 553471, 559785, 561150, 561151, 565247, 566719, 567065, 568274, 568275, 574006, 574007, 574347, 575865, 577230, 577231, 579327, 580967, 581502, 581503, 581883, 583079, 588543, 589439, 604708, 604709, 604710, 604713, 606847, 608111, 612046, 612047, 612967, 620971, 622654, 622655, 623295, 626331, 629759, 630527, 631295, 637057, 637948, 637949, 637950, 639310, 639311, 640641, 645756, 645757, 645758, 645759, 646140, 646141, 646142, 647849, 649385, 650889, 654191, 654571, 654619, 655359, 655961, 656415, 665067, 665215, 666111, 667375, 669921, 680300, 680301, 680302, 680303, 687871, 688553, 689639, 695067, 698593, 699049, 700487, 704511, 704623, 713575, 716689, 716690, 716691, 717694, 717695, 719225, 720722, 720723, 723945, 725387, 726057, 726478, 726479, 726910, 726911, 728831, 730559, 732251, 736393, 736447, 737956, 737957, 737958, 737961, 747291, 748031, 748201, 750831, 753662, 753663, 755625, 756086, 756087, 757698, 757699, 763675, 765340, 765341, 765342, 769641, 774622, 774623, 775337, 775787, 777435, 777438, 777439, 780391, 780735, 781951, 782335, 785918, 785919, 786431, 787739, 788583, 796775, 803871, 806276, 806277, 806278, 806283, 807407, 809129, 810814, 810815, 814439, 815871, 816060, 816061, 816062, 816815, 817289, 817775, 822139, 823783, 824187, 827391, 827961, 828443, 829087, 830204, 830205, 830206, 830207, 833775, 837799, 839678, 839679, 840702, 840703, 841726, 841727, 844647, 847871, 849409, 850079, 850596, 850597, 850598, 851227, 852412, 852413, 852414, 854191, 856731, 859135, 859719, 861009, 861010, 861011, 861521, 861522, 861523, 863798, 863799, 865846, 865847, 868991, 870171, 871451, 872254, 872255, 872761, 872825, 874614, 874615, 874619, 882815, 884159, 886207, 886555, 886953, 889833]
```

**Comment by Domanic** [comment]
Please make the changes in the files.

**Comment by DinhH** [comment]
I've changed most of the values to just 5 digits.

**Pull request merged**
