### PR TITLE
my public tests

### PR DESCRIPTION
**Pull request by brandonLJackson**

### CODE REVIEW

**Comment by Domanic** [comment]
The number of acceptance tests should be between 100 and 200. Can you please fix them?

**Comment by brandonLJackson** [comment]
There you go, that should fall within that range. Do I need to make a new request or will that do?

**Comment by cindywu2018** [comment]
Your tests are now good. However, please rename your files so they don't contain any upper case letters. Thanks!

**Comment by brandonLJackson** [comment]
Alright, done and done.

**Comment by cindywu2018** [comment]
Perfect, thank you!

**Pull request merged**
